#!/bin/bash

###  LS_COLORS ###
LS_COLORS=''
LS_COLORS+='no=0;39:'   # global default
LS_COLORS+='di=0;36:'   # directory
LS_COLORS+='ex=0;32:'   # executable file
LS_COLORS+='fi=0;39:'   # file
LS_COLORS+='ec=:'       # non-filename text
LS_COLORS+='mi=1;31:'   # non-existent file pointed to by a symlink
LS_COLORS+='ln=target:' # symbolic link
LS_COLORS+='or=31;01'   # symbolic link pointing to a non-existent file

export LS_COLORS
export GREP_COLOR='1;33'

### ENABLE COLORS ###
#alias dir='dir --color=auto'
#alias egrep='egrep --color=auto'
#alias fgrep='fgrep --color=auto'
#alias grep='grep --color=auto'
#alias ls='ls --color=auto'
#alias vdir='vdir --color=auto'


### PROMPT ###
if [[ $COLORTERM = gnome-* && $TERM = xterm ]]  && infocmp gnome-256color >/dev/null 2>&1; then export TERM=gnome-256color
elif [[ $TERM != dumb ]] && infocmp xterm-256color >/dev/null 2>&1; then export TERM=xterm-256color
fi

if tput setaf 1 &> /dev/null; then
    tput sgr0
    if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
      MAGENTA=$(tput setaf 9)
      ORANGE=$(tput setaf 172)
      GREEN=$(tput setaf 190)
      PURPLE=$(tput setaf 141)
      WHITE=$(tput setaf 0)
    else
      MAGENTA=$(tput setaf 5)
      ORANGE=$(tput setaf 4)
      GREEN=$(tput setaf 2)
      PURPLE=$(tput setaf 1)
      WHITE=$(tput setaf 7)
    fi
    BOLD=$(tput bold)
    RESET=$(tput sgr0)
else
    MAGENTA="\033[1;31m"
    ORANGE="\033[1;33m"
    GREEN="\033[1;32m"
    PURPLE="\033[1;35m"
    WHITE="\033[1;37m"
    BOLD=""
    RESET="\033[m"
fi

parse_git_dirty () {
  if [[ $(git status 2> /dev/null | tail -n1 | cut -c 1-17) != "nothing to commit" ]]; then
    echo " ✗"
  else
    echo " ✓"
  fi
}
parse_git_branch () {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

PS1="\[${BOLD}${MAGENTA}\]\u \[$WHITE\]at \[$ORANGE\]\h \[$WHITE\]in \[$GREEN\]\w\[$WHITE\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$PURPLE\]\$(parse_git_branch)\[$WHITE\]\n\$ \[$RESET\]"

# Demo Prompt
#PS1="\[${BOLD}$MAGENTA\]\w\[$WHITE\]\n$ \[$RESET\]"
